/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by client-gen. DO NOT EDIT.

// This package contains the scheme of the automatically generated clientset.
package scheme
