apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: stand
spec:
  homepage: https://github.com/dodopizza/stand-schedule-policy-controller
  shortDescription: Startup or shutdown command stand and associated resources
  version: {{ .TagName }}
  description: |
    Plugin for starting up or shutting down Kubernetes applications located in dedicated namespace 
    and associated cloud resources. This plugin override startup or shutdown time for corresponding StandSchedulePolicy object
  caveats: |
    None
  platforms:
    - {{addURIAndSha "https://github.com/dodopizza/stand-schedule-policy-controller/releases/download/{{ .TagName }}/kubectl-stand_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-stand
      files:
        - from: kubectl-stand
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - {{addURIAndSha "https://github.com/dodopizza/stand-schedule-policy-controller/releases/download/{{ .TagName }}/kubectl-stand_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-stand
      files:
        - from: kubectl-stand
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - {{addURIAndSha "https://github.com/dodopizza/stand-schedule-policy-controller/releases/download/{{ .TagName }}/kubectl-stand_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-stand
      files:
        - from: kubectl-stand
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - {{addURIAndSha "https://github.com/dodopizza/stand-schedule-policy-controller/releases/download/{{ .TagName }}/kubectl-stand_Linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-stand
      files:
        - from: kubectl-stand
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - {{addURIAndSha "https://github.com/dodopizza/stand-schedule-policy-controller/releases/download/{{ .TagName }}/kubectl-stand_Windows_x86_64.zip" .TagName | indent 6 }}
      bin: kubectl-stand.exe
      files:
        - from: kubectl-stand.exe
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: windows
          arch: amd64
