/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated typed clients.
package v1
