/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	v1 "github.com/dodopizza/stand-schedule-policy-controller/pkg/apis/standschedules/v1"
	"github.com/dodopizza/stand-schedule-policy-controller/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type StandSchedulesV1Interface interface {
	RESTClient() rest.Interface
	StandSchedulePoliciesGetter
}

// StandSchedulesV1Client is used to interact with features provided by the automation.dodois.io group.
type StandSchedulesV1Client struct {
	restClient rest.Interface
}

func (c *StandSchedulesV1Client) StandSchedulePolicies() StandSchedulePolicyInterface {
	return newStandSchedulePolicies(c)
}

// NewForConfig creates a new StandSchedulesV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*StandSchedulesV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new StandSchedulesV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*StandSchedulesV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &StandSchedulesV1Client{client}, nil
}

// NewForConfigOrDie creates a new StandSchedulesV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *StandSchedulesV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new StandSchedulesV1Client for the given RESTClient.
func New(c rest.Interface) *StandSchedulesV1Client {
	return &StandSchedulesV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *StandSchedulesV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
