/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/dodopizza/stand-schedule-policy-controller/pkg/apis/standschedules/v1"
	scheme "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StandSchedulePoliciesGetter has a method to return a StandSchedulePolicyInterface.
// A group's client should implement this interface.
type StandSchedulePoliciesGetter interface {
	StandSchedulePolicies() StandSchedulePolicyInterface
}

// StandSchedulePolicyInterface has methods to work with StandSchedulePolicy resources.
type StandSchedulePolicyInterface interface {
	Create(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.CreateOptions) (*v1.StandSchedulePolicy, error)
	Update(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.UpdateOptions) (*v1.StandSchedulePolicy, error)
	UpdateStatus(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.UpdateOptions) (*v1.StandSchedulePolicy, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.StandSchedulePolicy, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.StandSchedulePolicyList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StandSchedulePolicy, err error)
	StandSchedulePolicyExpansion
}

// standSchedulePolicies implements StandSchedulePolicyInterface
type standSchedulePolicies struct {
	client rest.Interface
}

// newStandSchedulePolicies returns a StandSchedulePolicies
func newStandSchedulePolicies(c *StandSchedulesV1Client) *standSchedulePolicies {
	return &standSchedulePolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the standSchedulePolicy, and returns the corresponding standSchedulePolicy object, and an error if there is any.
func (c *standSchedulePolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.StandSchedulePolicy, err error) {
	result = &v1.StandSchedulePolicy{}
	err = c.client.Get().
		Resource("standschedulepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StandSchedulePolicies that match those selectors.
func (c *standSchedulePolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.StandSchedulePolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.StandSchedulePolicyList{}
	err = c.client.Get().
		Resource("standschedulepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested standSchedulePolicies.
func (c *standSchedulePolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("standschedulepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a standSchedulePolicy and creates it.  Returns the server's representation of the standSchedulePolicy, and an error, if there is any.
func (c *standSchedulePolicies) Create(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.CreateOptions) (result *v1.StandSchedulePolicy, err error) {
	result = &v1.StandSchedulePolicy{}
	err = c.client.Post().
		Resource("standschedulepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(standSchedulePolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a standSchedulePolicy and updates it. Returns the server's representation of the standSchedulePolicy, and an error, if there is any.
func (c *standSchedulePolicies) Update(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.UpdateOptions) (result *v1.StandSchedulePolicy, err error) {
	result = &v1.StandSchedulePolicy{}
	err = c.client.Put().
		Resource("standschedulepolicies").
		Name(standSchedulePolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(standSchedulePolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *standSchedulePolicies) UpdateStatus(ctx context.Context, standSchedulePolicy *v1.StandSchedulePolicy, opts metav1.UpdateOptions) (result *v1.StandSchedulePolicy, err error) {
	result = &v1.StandSchedulePolicy{}
	err = c.client.Put().
		Resource("standschedulepolicies").
		Name(standSchedulePolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(standSchedulePolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the standSchedulePolicy and deletes it. Returns an error if one occurs.
func (c *standSchedulePolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("standschedulepolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *standSchedulePolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("standschedulepolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched standSchedulePolicy.
func (c *standSchedulePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.StandSchedulePolicy, err error) {
	result = &v1.StandSchedulePolicy{}
	err = c.client.Patch(pt).
		Resource("standschedulepolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
