/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// StandSchedulePolicies returns a StandSchedulePolicyInformer.
	StandSchedulePolicies() StandSchedulePolicyInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// StandSchedulePolicies returns a StandSchedulePolicyInformer.
func (v *version) StandSchedulePolicies() StandSchedulePolicyInformer {
	return &standSchedulePolicyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
