/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	standschedulesv1 "github.com/dodopizza/stand-schedule-policy-controller/pkg/apis/standschedules/v1"
	versioned "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/listers/standschedules/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StandSchedulePolicyInformer provides access to a shared informer and lister for
// StandSchedulePolicies.
type StandSchedulePolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.StandSchedulePolicyLister
}

type standSchedulePolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewStandSchedulePolicyInformer constructs a new informer for StandSchedulePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStandSchedulePolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStandSchedulePolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredStandSchedulePolicyInformer constructs a new informer for StandSchedulePolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStandSchedulePolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StandSchedulesV1().StandSchedulePolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StandSchedulesV1().StandSchedulePolicies().Watch(context.TODO(), options)
			},
		},
		&standschedulesv1.StandSchedulePolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *standSchedulePolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStandSchedulePolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *standSchedulePolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&standschedulesv1.StandSchedulePolicy{}, f.defaultInformer)
}

func (f *standSchedulePolicyInformer) Lister() v1.StandSchedulePolicyLister {
	return v1.NewStandSchedulePolicyLister(f.Informer().GetIndexer())
}
