/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// StandSchedulePolicyListerExpansion allows custom methods to be added to
// StandSchedulePolicyLister.
type StandSchedulePolicyListerExpansion interface{}
