/*
Copyright Dodo Engineering

Authored by The Infrastructure Platform Team.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/dodopizza/stand-schedule-policy-controller/pkg/client/clientset/versioned/typed/standschedules/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeStandSchedulesV1 struct {
	*testing.Fake
}

func (c *FakeStandSchedulesV1) StandSchedulePolicies() v1.StandSchedulePolicyInterface {
	return &FakeStandSchedulePolicies{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeStandSchedulesV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
