name: ci

on:
  push:
    branches:
      - "main"

env:
  GOLANG_VERSION: "^1.18.2"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Set up go mod cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Debugging action
      # - name: Set up tmate
      #   uses: mxschmitt/action-tmate@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: "--fix=false --timeout=10m"
          skip-go-installation: true

      - name: Tidy
        run: make tidy

      - name: Login to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit test
        run: make test-unit

      - name: Set up Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1
          skipClusterCreation: true

      - name: Set up Integration test
        run: make test-integration-setup

      - name: Integration test
        run: make test-integration

      - name: Push
        run: make DOCKER_IMAGE_REGISTRY="ghcr.io/dodopizza" push-docker