name: plugin

on:
  push:
    tags:
      - "*"

env:
  GOLANG_VERSION: "^1.18.2"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # unused until https://github.com/rajatjindal/krew-release-bot/issues/47 resolved
      # - name: Update new version in krew-index
      #   if: ${{ !contains(github.ref, 'beta') }}
      #   uses: rajatjindal/krew-release-bot@v0.0.43
      #   env:
      #     UPSTREAM_KREW_INDEX_REPO_NAME: krew-index
      #     UPSTREAM_KREW_INDEX_REPO_OWNER: dodopizza
